fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib'
      branch: '4.7.x'
    xinetd: 'git://github.com/puppetlabs/puppetlabs-xinetd'
  symlinks:
    tftp: "#{source_dir}"
