fixtures:
  repositories:
    augeas_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-augeas_core'
      puppet_version: '>= 6.0.0'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    xinetd: 'git://github.com/puppetlabs/puppetlabs-xinetd'
