fixtures:
  repositories:
    augeas_core: 'https://github.com/puppetlabs/puppetlabs-augeas_core'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    xinetd: 'git://github.com/puppetlabs/puppetlabs-xinetd'
